version: '3.8'
services:
  server:
    build: ./server
    container_name: backend
    ports:
      - '3001:3001'
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    # command: /usr/app/node_modules/.bin/nodemon app.mjs
    command: nodemon -L app.mjs
  client:
    build: ./client
    command: npm start
    container_name: frontend
    depends_on:
      - server
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    # stdin_open: true
    # tty: true